pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your Git repository
                git 'https://github.com/iamkarn007/Phase5Project.git'
            }
        }
        stage('Test') {
            steps {
                // Build and test your Spring Boot application
                sh 'mvn clean test'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build the Docker image using the Dockerfile in your repository
                sh 'docker build -t iamkarn07/phase5project:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                // Push the Docker image to Docker Hub
                sh 'docker login -u iamkarn07 -p **************'
                sh 'docker push iamkarn07/phase5project:latest'
            }
        }
    }
}
