pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your Git repository
                git 'https://github.com/iamkarn07/your-springboot-app.git'
            }
        }
        stage('Test') {
            steps {
                // Build and test your Spring Boot application
                sh 'mvn clean test'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build the Docker image using the Dockerfile in your repository
                sh 'docker build -t your-dockerhub-username/your-springboot-app:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                // Push the Docker image to Docker Hub
                sh 'docker login -u your-dockerhub-username -p your-dockerhub-password'
                sh 'docker push your-dockerhub-username/your-springboot-app:latest'
            }
        }
    }
}
