pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
              
                git 'https://github.com/iamkarn007/Phase5Project.git'
            }
        }
        stage('Test') {
            steps {
            
                sh 'mvn clean test'
            }
        }
        stage('Build Docker Image') {
            steps {
           
                sh 'docker build -t iamkarn07/phase5project:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker login -u iamkarn07 -p **************'
                sh 'docker push iamkarn07/phase5project:latest'
            }
        }
    }
}
